In [1]:
import numpy as np

In [8]:
mat1 = np.random.randint(0, 500, (10,10))
print(mat1)

[[ 17 448  80  78  61 457 454 171  19 442]
 [373 163 417 445  28 109 115  62 159 362]
 [103 446  97  61 298  94 352 331 357 481]
 [ 97 169  80 196 366 208 370 228 202 183]
 [163  29  65   0 223 443 364 118 299 299]
 [490  69 121 365 347 268  62 197 146 499]
 [252 173  45 452 343 204  11 345 448 395]
 [484 409 448  72 120 498 271 143 458 331]
 [322 204  37 264 418  21 238 142   3  89]
 [330  57  36 441 106  32 463 157 416 374]]


In [9]:
mat1[0, 0]

17

In [10]:
mat1[mat1 > 250]

array([448, 457, 454, 442, 373, 417, 445, 362, 446, 298, 352, 331, 357,
       481, 366, 370, 443, 364, 299, 299, 490, 365, 347, 268, 499, 252,
       452, 343, 345, 448, 395, 484, 409, 448, 498, 271, 458, 331, 322,
       264, 418, 330, 441, 463, 416, 374])

In [11]:
#Birim (Identity) Matris

In [12]:
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
D = np.diag([1,2,3,4,5,6,7,8,9])
D

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [15]:
#Üçgen (Triangular) Matris, tril/triu

In [16]:
M = np.random.randn(5, 5)
U = np.triu(M)
L = np.tril(M)
print(M)
print('\n')
print(U)
print('\n')
print(L)

[[ 1.07614129  0.42024585  1.7704747   0.91609024 -0.27608415]
 [-0.6193106   0.4803389   0.06543799 -0.65606788 -0.03036935]
 [-0.50580023  1.4284815   1.4891072  -0.89019312 -0.90709606]
 [-0.29672909  1.18719694  1.8348988   1.85702974 -1.94958727]
 [ 0.29552201 -0.17674802 -1.00921602  0.36047565 -0.94646415]]


[[ 1.07614129  0.42024585  1.7704747   0.91609024 -0.27608415]
 [ 0.          0.4803389   0.06543799 -0.65606788 -0.03036935]
 [ 0.          0.          1.4891072  -0.89019312 -0.90709606]
 [ 0.          0.          0.          1.85702974 -1.94958727]
 [ 0.          0.          0.          0.         -0.94646415]]


[[ 1.07614129  0.          0.          0.          0.        ]
 [-0.6193106   0.4803389   0.          0.          0.        ]
 [-0.50580023  1.4284815   1.4891072   0.          0.        ]
 [-0.29672909  1.18719694  1.8348988   1.85702974  0.        ]
 [ 0.29552201 -0.17674802 -1.00921602  0.36047565 -0.94646415]]


In [17]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [20]:
#Satır-Sütun SWAP (Yer Değiştirme) İşlemleri

In [21]:
m1 = np.arange(0, 16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
m1[[0, 1]] = m1[[1, 0]]
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
m2 = np.arange(0, 36).reshape(6, 6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [26]:
m2[:,[0,1]] = m2[:,[1,0]]
m2

array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23],
       [25, 24, 26, 27, 28, 29],
       [31, 30, 32, 33, 34, 35]])

In [27]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,1], [1,1]])
C = np.concatenate((A,B))
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

In [28]:
#Transpoze

In [29]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print('Matrix(M) ==> \n', M)
print('\n')
print('Transpose of M ==> \n', np.transpose(M))
print('\n')
#OR
print(M.T)

Matrix(M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]


Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [30]:
#Determinant
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.det(M))

195.0


In [31]:
#Rank
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.matrix_rank(M))

3


In [32]:
#Ters Alma
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.inv(M))

[[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [33]:
#Matrislerin Kuvveti

In [34]:
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [35]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [36]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [37]:
#TENSÖRLER

In [38]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100, 200, 300], [400, 500, 600], [700,800,900]]
])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [39]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]]
])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [40]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [41]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [42]:
S = T1 - T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [43]:
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [45]:
P = T1*T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [46]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [47]:
D = T1 / T2
D

<ipython-input-47-f9444d3a0924>:1: RuntimeWarning: divide by zero encountered in true_divide
  D = T1 / T2


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [48]:
np.divide(T1, T2)

<ipython-input-48-b885ab1f8362>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(T1, T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [49]:
np.tensordot(T1, T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

In [50]:
#Denklem Çözme, AX = B

In [51]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
B = np.random.random((3,1))
B

array([[0.36778434],
       [0.6544787 ],
       [0.86793236]])

In [53]:
X = np.dot(np.linalg.inv(A), B)
X

array([[-2.30892716e+14],
       [ 4.61785432e+14],
       [-2.30892716e+14]])

In [54]:
X = np.matmul(np.linalg.inv(A), B)
X

array([[-2.30892716e+14],
       [ 4.61785432e+14],
       [-2.30892716e+14]])

In [55]:
X = np.linalg.inv(A)@B
X

array([[-2.30892716e+14],
       [ 4.61785432e+14],
       [-2.30892716e+14]])

In [56]:
X = np.linalg.solve(A, B)
X

array([[-2.30892716e+14],
       [ 4.61785432e+14],
       [-2.30892716e+14]])

In [57]:
#SCIPY , import scipy as sp

In [58]:
#scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack, scipy.signal, 
#scipy.stats, scipy.ndimage, scipy.io

In [60]:
from scipy import linalg
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)
print(linalg.inv(A).dot(b)) #slow
print(np.linalg.solve(A, b)) #fast

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
[[-9.28]
 [ 5.16]
 [ 0.76]]
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [61]:
#Scipy ile integral alma

In [62]:
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [65]:
from scipy import special 
result = integrate.quad(lambda x : special.jv(2.5, x), 0, 4.5)
print(result)

(1.1178179380783244, 7.866317216380707e-09)


In [64]:
#Türev Alma

In [66]:
from scipy.misc import derivative
def f(x):
    return x**3 + x**2

D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [67]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [68]:
#Seriler

In [69]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [70]:
s1.dtype

dtype('int32')

In [71]:
s1.nbytes

28

In [72]:
s1.shape

(7,)

In [73]:
len(s1)

7

In [74]:
s1.count()

7

In [76]:
s1.size

7

In [77]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [78]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [79]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.18425782, 0.96793079, 0.78495762, 0.4442217 , 0.62779527,
        0.27812477, 0.87287463, 0.882783  , 0.75796674, 0.87314523]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.184258
 1    0.967931
 2    0.784958
 3    0.444222
 4    0.627795
 5    0.278125
 6    0.872875
 7    0.882783
 8    0.757967
 9    0.873145
 dtype: float64)

In [80]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [81]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [82]:
#Serileri Bölme (Slicing)

In [83]:
s

0    0.184258
1    0.967931
2    0.784958
3    0.444222
4    0.627795
5    0.278125
6    0.872875
7    0.882783
8    0.757967
9    0.873145
dtype: float64

In [84]:
s[:]

0    0.184258
1    0.967931
2    0.784958
3    0.444222
4    0.627795
5    0.278125
6    0.872875
7    0.882783
8    0.757967
9    0.873145
dtype: float64

In [85]:
s[0:3]

0    0.184258
1    0.967931
2    0.784958
dtype: float64

In [86]:
s[-1:]

9    0.873145
dtype: float64

In [87]:
s[:-2]

0    0.184258
1    0.967931
2    0.784958
3    0.444222
4    0.627795
5    0.278125
6    0.872875
7    0.882783
dtype: float64

In [88]:
s[-3:-1]

7    0.882783
8    0.757967
dtype: float64

In [89]:
#Serilere Eleman Ekleme (Append)

In [90]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [91]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [92]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [93]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [94]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [95]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [96]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [97]:
s4 = s4.append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [ ]:
#Seriler üzerindeki operasyonlar