In [1]:
dict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Doctorate'}
print("dict['Name']:", dict['Name'])
print("dict['Age']:", dict['Age'])

dict['Name']: Fırat
dict['Age']: 50


In [2]:
dict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Doctorate'}
dict['Age'] = 30
dict['School'] = "University"

In [3]:
print("dict['Age']:", dict['Age'])
print("dict['School']:", dict['School'])

dict['Age']: 30
dict['School']: University


In [4]:
dict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Doctorate', 'Name' : 'Oğuz'}
print("dict['Name']:", dict['Name'])

dict['Name']: Oğuz


In [5]:
#silme
dict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Doctorate'}
del dict['Name']
dict.clear()
del dict

In [6]:
print("dict['Age']:", dict['Age'])
print("dict['School']:", dict['School'])

TypeError: 'type' object is not subscriptable

In [7]:
#get() ve items() metotları

In [8]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [10]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222', 'Joanne' : '555-3333'}
for key, value in phonebook.items():
    print(key, value, sep=' -> ')

Chris -> 555-1111
Katie -> 555-2222
Joanne -> 555-3333


In [11]:
import numpy as np
import warnings 
warnings.filterwarnings("ignore")

In [12]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [13]:
type(list1)

list

In [14]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [15]:
arr1.data

In [16]:
type(arr1)

numpy.ndarray

In [17]:
arr1.dtype

dtype('int32')

In [18]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [19]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
np.arange(100, 0, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [22]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [23]:
arr3.nbytes

40

In [24]:
len(arr3)

10

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [28]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [29]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [30]:
a = np.array([10,20,30])
np.full(3, a)

array([10, 20, 30])

In [31]:
ar1 = np.arange(1,20)
ar1[ar1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
ar1 = np.arange(1,20)
ar1[ar1 %2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [34]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [35]:
np.random.random(4)

array([0.3483587 , 0.36338576, 0.43861433, 0.92448868])

In [36]:
np.random.randint(0, 500, 5)

array([180,  77, 359, 285, 278])

In [37]:
np.random.randint(0, 500, 10)

array([129,  88, 155, 362, 320, 252, 272, 272, 218,   8])

In [38]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [39]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [40]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [41]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [42]:
np.random.seed(101000)
np.random.randint(0, 100, 10)

array([77, 65, 27, 79, 88, 19, 82, 41, 38, 62])

In [52]:
np.random.seed(4294000000)
np.random.randint(0, 100, 10)

array([ 1, 21, 96, 25, 44, 83, 41, 58,  0, 93])

In [53]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.37699054, 8.88293199, 8.58321049, 5.16842618, 6.08338144,
       7.88871613, 6.47568466, 7.08649656, 8.15765161, 9.81507636])

In [54]:
np.floor(f1)

array([6., 8., 8., 5., 6., 7., 6., 7., 8., 9.])

In [55]:
np.trunc(f1)

array([6., 8., 8., 5., 6., 7., 6., 7., 8., 9.])

In [56]:
f1.astype(int)

array([6, 8, 8, 5, 6, 7, 6, 7, 8, 9])

In [57]:
b2 = np.random.randn(10)
b2

array([ 0.23807536,  0.78279102,  0.80837183, -0.19499632,  2.40366735,
        0.29376823,  0.89313794, -1.70593055,  0.63418143, -2.19669777])

In [58]:
arr1

array([10, 20, 30, 40, 50, 60])

In [59]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [60]:
#Numpy Dizi Operasyonları

In [61]:
arr2 = np.arange(1, 20)

In [62]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [63]:
arr2.sum()

190

In [64]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [65]:
#min(), max(), argmin(), argmax(), mean(), median()

In [66]:
np.var(arr2)

30.0

In [67]:
np.std(arr2)

5.477225575051661

In [68]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [69]:
A.sum()

129

In [70]:
#max(), min(), mean(), median()

In [71]:
np.amin(A, axis = 0) #sütun tabanlı minimum değeri bulur

array([1, 2, 1, 0])

In [72]:
np.amin(A, axis = 1) #satır tabanlı minimum değeri bulur

array([0, 5, 1, 3])

In [73]:
np.var(A)

40.30859375

In [74]:
np.std(A)

6.348904925260734

In [75]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [76]:
a = np.array([7,5,3,9,0,2])
a[0]

7

In [77]:
a[1:]

array([5, 3, 9, 0, 2])

In [78]:
a[1:4]

array([5, 3, 9])

In [79]:
a[-1]

2

In [80]:
a[-3:-1]

array([9, 0])

In [81]:
#Dizi üzerinde eleman değişiklikleri

In [82]:
ar = np.arange(1, 30)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [83]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23  0
 25  0 27  0 29]


In [84]:
ar2 = np.array([10,20,30,10,10,20,20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [85]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [86]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [88]:
#Eksik değerlerle ilgilenme

In [89]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [90]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [91]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [92]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [93]:
np.isnan(a).any()

False

In [94]:
A = np.array([[1,2,np.nan,4], [np.nan,6,7,8], [10,np.nan,12,13], [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [95]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [96]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [97]:
#Dizileri Yatay/Dikey olarak birbirine ekleme

In [98]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [99]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [100]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [101]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [102]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

np.intersect1d(c1, c2)

array([20, 40, 60])

In [103]:
np.setdiff1d(c1, c2)

array([10, 30, 50])

In [104]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

np.where(a == b)

(array([1, 4], dtype=int64),)

In [105]:
a[np.where(a == b)]

array([2, 8])

In [106]:
a1 = np.arange(0, 60)
a1[np.where((a1 > 20 ) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [107]:
a1 = np.arange(0, 60)
a1[np.where(((a1 > 20 ) & (a1 < 35)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [108]:
a1 = np.arange(0, 60)
a1[np.where(np.logical_and(a1 > 20, a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])